<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <title>Alexander Kraus Architektur</title>
        <meta http-equiv="Content-Script-Type" content="text/javascript" />
        <meta http-equiv="imagetoolbar" content="no" />
        <meta name="keywords" content="architekt, architekten, architektensuche, architektenwettbewerb, architektur, architekturb&uuml;ro,  baukunst, baukultur,  b&uuml;roraumplanung, b&uuml;rofl&auml;chenplanung,  innenarchitekt, innenarchitekten, innenarchitektur, innenarchitekturb&uuml;ro,  store-design, corporate identity, corporate architecture,  wohnungsbau, gewerbebau, verwaltungsbau,  design, objektdesign,  entwerfen, entwerfer, entwurf, entwurfsplanung,  gestalten, gestalter, gestaltung,  planer, planung, planungsb&uuml;ro,  innenraumplanung, hochbau, hochbauplanung,  stadtplaner, stadtplanung, st&auml;dtebau,  bochum, dortmund, essen, duisburg, unna, hamm, arnsberg, ruhrgebiet, wettbewerb, wettbewerbe, wettbewerbsbeitrag, wettbewerbsteilnahme,  dortmunder u, u-turm, u2021" />
        <meta name="description" content="Alexander Kraus Architekturen" />
        <link rel="stylesheet" href="/aka/includes/css/screen.css" type="text/css" media="print, projection, screen" />
        <script src="/aka/includes/js/jquery-1.2.1.min.js" type="text/javascript"></script>
        <script src="/aka/includes/js/global.js" type="text/javascript"></script>
    </head>