<ul class="navigation">
    <li>
        <ul class="first">
            <li class="selected"><a href="/index.php">B&uuml;ro</a></li>
            <li>/&nbsp;Projekte</li>
        </ul>
        <ul class="second">
            <li class="selected">Leistungen</li>
            <li>/&nbsp;Daten</li>
        </ul>
        <ul class="third">
            <li class="selected">Architektur</li>
            <li>/&nbsp;Konzepte</li>
            <li>/&nbsp;Energie</li>
            <li>/&nbsp;Referenzen</li>
            <li>/&nbsp;Standpunkte</li>
        </ul>
    </li>
</ul>